# This is a basic workflow to help you get started with Actions

name: Cleanup Caprover Images

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  run-cleanup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run Caprover Cleanup
        run: |
          yarn
          yarn tsc
          node ./dist/main.js cleanup -p ${{ secrets.CAPROVER_PASSWORD }}
        
